### ISSUE TITLE
Feature Request: Hooks

### ISSUE THREAD

**Issue by fdw** [nils-werner/crestic#11]
After the backup ran its course, I like to send a notification (especially if it failed). Currently, I do this in a custom shell script, but that is no longer feasible.
Instead I would propose something like this:
```
[home]
on_success: <your command>
on_fail: <another command>
```

It would be even better if you could set hooks per command, like this:
```
[home.backup]
on_fail: <command>

[home.prune]
on_success: <command>
on_fail: <command>
```

Do you think this would be in scope for `crestic`?

**Comment by nils-werner** [comment]
This is out of scope for this project, and can be simply in your shell:

    crestic home backup && success_command || fail_command

**Comment by fdw** [comment]
Okay, thank you 🙂
