### ISSUE TITLE
[no issue] project collaboration

### ISSUE THREAD

**Issue by akisys** [nils-werner/crestic#17]
Hi there,

I just discovered your very useful project and saw some similarities to my own [https://github.com/akisys/restic-backup](https://github.com/akisys/restic-backup), which I started a while back in a private repo.
Maybe you are interested in a collaboration and exchanging ideas.

Let me know what you think.
Cheers, Alex.

**Comment by nils-werner** [comment]
Hey Alex, that's cool! And sure, such a collaboration would be interesting. If you have any suggestions or questions, make sure to drop by!
