### ISSUE TITLE
[idea] Use a config directory (conf.d)

### ISSUE THREAD

**Issue by fancsali** [nils-werner/crestic#19]
Besides putting all the different sections into one central file, it'd be a great option to let the user specify a directory, and merge and parse all the different files in there. Pretty similar how `conf.d` directories work in many linux distributions.

This would simplify management of the configurations in automatically deployed infrastructure.

*NOTE*: A way of achieving this is using an include directive.

**Comment by nils-werner** [comment]
I was toying with this idea before. A possible implementation is provided by [confight](https://pypi.org/project/confight/)

> NOTE: A way of achieving this is using an include directive.

what do you mean?

**Comment by redstreet** [comment]
confight / conf.d would be awesome. This would allow another level of inheritance, as each file would be able to have its own global. Any chance this will be implemented?

Thanks for crestic BTW, it's awesome. Especially the "does not try to be clever" part, which makes it highly flexible, predictable, and usable!

**Comment by nils-werner** [comment]
I really like conf.d's for my OS configs, like /etc overriding /usr/lib, and ~/.config overriding /etc, but I have yet to come up with a scenario where I would want this for crestic.

Can you provide some use cases where this would be really necessary?

**Comment by redstreet** [comment]
I have several sets of profiles: one for each of my servers, and one for each laptop I own. Each of these has a set of globals, and several profiles that use these globals. With the current config, I can't use globals, and am forced to repeat global options across each group of profiles. conf.d would solve this:

conf.d/mainserver.cfg (with a global + multiple profiles dependent on that global)
conf.d/storageserver.cfg (ditto)
conf.d/laptop1.cfg (ditto)

PS: the overriding (~/.config over /etc, and so on) doesn't matter for my personal use case.

**Comment by nils-werner** [comment]
I am not sure if I am understanding your scenario correctly, because I don't believe it would work that way... the way you are describing it, the global values would be overwritten or merged anyways.

If you need different values for different machines or repos, just don't define them globally.

**Comment by redstreet** [comment]
Apologies, that was a rather ambiguous description. Here is an example:

conf.d/mainserver.cfg:
```
[global]
repo: rclone:hoolicloud:/restic
cache-dir: /tmp/resticcache
password-command: "/usr/bin/pass /restic/mainserver"

[root]
arguments: "/root"

[etc]
arguments: "/etc"

[serverhome]
arguments: "/home/server"
```

conf.d/laptop_primary.cfg:
```
[global]
repo: rclone:cloudone:/restic/backup/laptop
cache-dir: /home/.securecache
password-command: "/usr/local/bin/pass /cloudone/backup"

[notes]
arguments: "/mnt/z"

[docs]
arguments: "/home/my/docs"

[music]
arguments: "/home/my/music"

```

**Comment by nils-werner** [comment]
Thanks for the example. I don't believe `conf.d` will work here, because you will be getting a single, merged final config from your files:

```
[global]
repo: rclone:cloudone:/restic/backup/laptop
cache-dir: /home/.securecache
password-command: "/usr/local/bin/pass /cloudone/backup"

[root]
arguments: "/root"

[etc]
arguments: "/etc"

[serverhome]
arguments: "/home/server"

[notes]
arguments: "/mnt/z"

[docs]
arguments: "/home/my/docs"

[music]
arguments: "/home/my/music"
```

However what you can do is

```
[@mainserver]
repo: rclone:hoolicloud:/restic
cache-dir: /tmp/resticcache
password-command: "/usr/bin/pass /restic/mainserver"

[root@mainserver]
arguments: "/root"

[etc@mainserver]
arguments: "/etc"

[serverhome@mainserver]
arguments: "/home/server"

[@laptop]
repo: rclone:cloudone:/restic/backup/laptop
cache-dir: /home/.securecache
password-command: "/usr/local/bin/pass /cloudone/backup"

[notes@laptop]
arguments: "/mnt/z"

[docs@laptop]
arguments: "/home/my/docs"

[music@laptop]
arguments: "/home/my/music"
```

**Comment by redstreet** [comment]
Makes sense. Thanks for the `@` based suggestion, which likely suffices for my needs!

**Comment by nils-werner** [comment]
To reiterate how I understand `conf.d` works:

Firstly, all files found in any one `conf.d` directory get merged, with the later file overwriting values from earlier files. That means two files

```
# /usr/lib/crestic/config.d/00-something.cfg
[global]
repo = foo
password = bar
```

```
# /usr/lib/crestic/config.d/01-else.cfg
[global]
repo = hello
cache-dir = /tmp/crestic
```

become a virtual config file

```
[global]
password = bar
repo = hello
cache-dir = /tmp/crestic
```

Secondly, there exist several such directories, which are loaded in a certain order to allow overloading:

 1. `/usr/lib/crestic/config.d/`
 1. `/etc/crestic.d/`
 1. `~/.config/crestic.d/`

That means you can overload values from the `/usr/lib/crestic/config.d/` files in `/etc/crestic.d/`. So add a file

```
# /etc/crestic.d/00-customization.cfg
[global]
repo = custom
```

and you will end up with a virtual config file

```
[global]
password = bar
repo = custom
cache-dir = /tmp/crestic
```

And same goes for `~/.config/crestic.d/`.

Why do this? For three reasons:

 1. Other packages can drop their config files into `/usr/lib/crestic/config.d/` to inject their config values without stepping on each other's toes by having to change one common config file.
 2. Packages put their default config files somewhere in `/usr`, i.e. `/usr/lib/crestic/config.d/`. If a system administrator wants to change those default values for a single machine, they can do so by overriding those values in `/etc/crestic.d/`, without having to change files in `/usr` (which are managed by the package manager).
 3. If now a single user wants to further change those default values, they can do so in `~/.config/crestic.d/`, without having to change files in `/usr/` or `/etc/` (which they can't edit anyways).

So do I need this in crestic?

 1. There are no packages that depend on crestic, so basically nobody wants to drop their config values in `/usr/lib/crestic/config.d/`
 2. I don't believe there are many config values that should be set by default by the package. You could argue that you could set some convenience values like

    ```
    [home@.backup]
    arguments: "~"

    [etc@.backup]
    arguments: "/etc"
    ```

    so you only need to define an `[@repo]` section and will immediately have `home@repo` and `etc@repo` available. But I am not sure if this little bit of convenience is that useful.

3. Same goes for users overriding system-settings. I don't think that pre-populated values are that necessary.

So unless I am misunderstanding how `conf.d` works, or am missing some really useful scenario, I don't see a need for it in this tool. If you find such a scenario, feel free to reopen this issue.
