### ISSUE TITLE
Multiple backup paths not recognized

### ISSUE THREAD

**Issue by dimejo** [nils-werner/crestic#20]
When using multiple paths for a backup with crestic v.0.6.0 I'm seeing an error like this:
```
/data/one /data/two does not exist, skipping
Fatal: all target directories/files do not exist
```
The config looks like this:
```
[data@.backup]
arguments: /data/one /data/two
tag: data
```
I've tried multiple variants of single and double quotes but to no avail. Multiple paths do work with crestic v0.3.0 (haven't tried any other versions yet).

**Comment by nils-werner** [comment]
Did you find a solution? My bet is on

```
arguments:
    /data/one
    /data/two
```

**Comment by nils-werner** [comment]
@dimejo Can you please post the solution that you've found, so that others can be helped as well?

**Comment by dimejo** [comment]
> @dimejo Can you please post the solution that you've found, so that others can be helped as well?

Well, there is no real solution. On that specific day I've been working for some hours non-stop and wasn't sure if it was crestic beeing buggy or me being tired and stupid. That's why I've switched back to my old working configuration and closed the issue.

I'll report back when I find the time to test this out again.

**Comment by nils-werner** [comment]
I just checked, the above solution works.
