### ISSUE TITLE
Ability to specify cwd

### ISSUE THREAD

**Issue by nettnikl** [nils-werner/crestic#23]
I'd like to propose a new feature - the ability to specify the cwd of the backup process. This seems to be a recurring pattern to allow relative path based backups (a use case is described at https://forum.restic.net/t/backing-up-restoring-relative-paths/744). This would be quite easy, as the `subprocess.call` supports the cwd parameter.

**Comment by nils-werner** [comment]
Agreed, that might be handy to have.

I'm thinking of introducing it as something like `_cwd:` and deprecating `arguments:` in favor of `_args:`, to prevent collisions with restic commandline options now or in the future.

**Comment by nils-werner** [comment]
I have pushed a few changes to `master`. Have a go and see if it works as expected.

**Comment by nettnikl** [comment]
Will do, thanks for your quick reaction!

**Comment by nettnikl** [comment]
Hey, finally had a chance to test on my setup, sorry for the delay.
It works, in the dry run as well as in my real setup! Great job!
One thing that it'd like considered looking at the resulting configs however - maybe a default backup path of "." would make sense, maybe only in cases where a path is given via cwd? What are your thoughts on this (or do you see discussion potential for another issue)?
Thanks again!

**Comment by nils-werner** [comment]
Great to hear!

You mean a file

```ini
[home]
    _cwd: ~
```

implies

```ini
[home]
    _cwd: ~
    _args: .
```

?

Hmm... I think woud prefer to not implement any opinionated (and maybe unexpected) behaviour, as I am merely trying to configure `restic` and its opinions.

**Comment by nettnikl** [comment]
Okay, i agree, i'm just looking for an option to have a "speaking" config file, as the idea of the option "_args: /path/to/backup" is not immediately clear for everyone. However, that has nothing to do with this request. I'll open a new ticket, this one is solved perfectly!

**Comment by nils-werner** [comment]
Lets keep this open until it has been merged into `master`.

**Comment by nils-werner** [comment]
Actually, I am playing with the idea of moving `_cwd` into the `[backup.environ]` key, because it is arguably an attribute of the execution `environment`, and not a command `option` or `argument`

**Comment by nils-werner** [comment]
Ok, I think I like it more that way: Your typical UNIX environment variables already contain `$PWD` that contains the current working directory. So it kind of makes sense to use this variable to change the cwd of restic:

```ini
[home]
_args: .

[home.environ]
PWD: ~
```

And you can also now cleanly override this value from the commandline

```sh
env PWD=~ crestic home backup
```

A small caveat: Normally, changing `$PWD` before running a command is not the same as changing the current cwd. Compare

```sh
(cd / && ls)
env PWD=/ ls
```

but I am ignoring that fact here.

**Comment by nettnikl** [comment]
While it technically is, i think it makes the config harder to read, which should also not be neglected. The current solution looks good to me - maybe you could show how the idiom i mentioned would look in with the alternative approach?

**Comment by nils-werner** [comment]
This is now in 0.8.0 and called `_workdir:`.
