### ISSUE TITLE
Concept: how to specify the unnamed restic parameters in a speaking way?

### ISSUE THREAD

**Issue by nettnikl** [nils-werner/crestic#24]
The backup command has an unnamed parameter to specify the backup path. To keep this software KISS compliant and unopinionated, nothing about this unnamed parameters is assumed - this includes the meaning of the parameter. However, the idea of the option "_args: /path/to/backup" is not immediately clear at first glance.
```
[home.backup]
_args: /path/to/backup  # Backup path
```
I'm not sure how to solve this issue - maybe anyone has an idea how to do so.
If it's out of scope, feel free to close the issue, for now i'll use the workaround to add a trailing line comment to annotate the `_cmd` line.

**Comment by nils-werner** [comment]
Well, the idea is that in the UNIX shell environment

```sh
command -a --bla hello world
```

`-a` and `--bla` are called *options* and `hello world` are called *arguments* or *args* for short.

Similarly in Python,

```python
def function(text, a=None, bla=None):
    pass
```

`a` and `bla` are *keyword arguments* or *kwargs* and `text` is an *argument* or *arg*.

That is why I called this key `argument:`, and I am now thinking about shortening it to `args:`.

And we are now thinking about introducing a key for the current working directory, for which `cwd:` would be a natural choice.

However, we are slowly increasing the likelyhood of producing a collision with the restic option keys `--arguments`, `--args`, and `--cwd`, should they ever be introduced. In Python there exists the convention of prefixing private attributes with single or double underscores: `self._private_attribute`. So tought it would make sense to use the same convention here, and use `_args:` for arguments and `_cwd:` for the current working directory.

**Comment by nettnikl** [comment]
Yes, sound reasonable. Even if the likelihood is small for a collision, i'd be happy to have my backup config to never break.
