### ISSUE TITLE
Config for boolean flags

### ISSUE THREAD

**Issue by ampedandwired** [nils-werner/crestic#3]
Nice project, thanks for putting this together. 

Is there a way to specify boolean flag arguments such as `--exclude-caches` or `--with-atime`? I couldn't seem to find a way to make it work.

Also is it possible to pass in extra arguments on the command line as well, for example `crestic home backup --verbose`?

**Comment by nils-werner** [comment]
> Is there a way to specify boolean flag arguments such as `--exclude-caches` or `--with-atime`? I couldn't seem to find a way to make it work.

Just using an empty field should work:

    exclude-caches:
    with-atime:

> Also is it possible to pass in extra arguments on the command line as well, for example `crestic home backup --verbose`?

Yes, it works exactly like this

**Comment by nils-werner** [comment]
Try the most recent version afee605

**Comment by ampedandwired** [comment]
Works like a charm, thanks!
