### ISSUE TITLE
Load environment variables from .env files

### ISSUE THREAD

**Issue by siddhantgoel** [nils-werner/crestic#31]
Thanks for creating & maintaining `crestic`! I've been using it for quite some time now and it works really well.

I'm trying to figure out if it's possible to load environment variables from env files or some other source, instead of specifying the key/value pairs directly in the config file. At the moment my `crestic.cfg` looks something like:

```
...
[global.environ]
B2_ACCOUNT_ID=abc
B2_ACCOUNT_KEY=def
...
```

If I check this file into git (which I do), those secret keys are also going to make their way into the git history which is not what I would like. So what I'm hoping for is some way for me to say:

```
[global.environ]
env_file=/path/to/.env
```

And then `crestic` would load the key/value pairs from this file instead. The advantage here would be that I could check an encrypted version of this `.env` file into git, and decrypt it before running `crestic`.

**Comment by nils-werner** [comment]
You could set them in your local environment.

**Comment by siddhantgoel** [comment]
Yeah that's one alternative, which makes them available to all the commands I run after they're set. I was looking for a way for them to be strictly available to the process that `crestic` runs and be gone afterwards.

**Comment by nils-werner** [comment]
Ah I just remembered a way: In the next version I will support `config.d/*` files, that means you can move the environment variables from `config.cfg` to `config.d/environ.cfg` and gitignore the file.

**Comment by siddhantgoel** [comment]
Ah nice, yeah that would work too!

**Comment by siddhantgoel** [comment]
Do you already have a rough timeline for the next release?

**Comment by nils-werner** [comment]
No, sorry. Right now I'm out of the country for a few months. But you can always just drop the latest `crestic.py` into your `~/.local/bin` to run the latest version.
