### ISSUE TITLE
crestic finds /etc/crestic.cfg but ignores it

### ISSUE THREAD

**Issue by AimoE** [nils-werner/crestic#33]
I am in the process of choosing a ui for restic, and I prefer simplicity over overwhelming support to features I don't need. I was doing fine with crestic at first, but then I tried reorganize the config files so that preset for the repositories and generic forget rules are in /etc/crestic.cfg and the rest are in user specific config files.

As I understand, this should work. The generic file in /etc doesn't even overlap the user specific settings in any way, not at this stage, anyway. Yet crestic keeps telling me:

`Fatal: Please specify repository location (-r or --repository-file)`

I tried out the debug option:

```
CRESTIC_DRYRUN=1 crestic home@myrepo forget
             Warning: Executing in debug mode. restic will not run, backups are not touched!
        Config files: /home/haltia/.config/crestic/crestic.cfg, /etc/crestic/crestic.cfg
   Config files used: /home/haltia/.config/crestic/crestic.cfg
     Config sections: global, global.forget, @myrepo, @myrepo.forget, home@, home@.forget, home@myrepo, home@myrepo.forget
Config sections used: 
        Env sections: global.environ, global.forget.environ, @myrepo.environ, @myrepo.forget.environ, home@.environ, home@.forget.environ, home@myrepo.environ, home@myrepo.forget.environ
   Env sections used: 
    Expanded command: restic forget
```

So crestic does find the config file in /etc but then decides not to use it. Why? I have not defined any of the CRESTIC_* environment variables.

All I have in the shared file at this stage is something like:

```
[@myrepo]
repo: /srv/myrepo

[@myrepo.forget]
keep-weekly:  52
keep-monthly: 48
prune:

[trim@myrepo.forget]
keep-within: 0y3m0d0h

[buoy@myrepo.forget]
keep-last: 9
```

(PS. I don't understand why the dry run lists sections that I haven't defined. For example, I have none of the global settings. What purpose does that serve?)

**Comment by nils-werner** [comment]
You say you have `/etc/crestic.cfg`, yet crestic is trying to read `/etc/crestic/crestic.cfg`.

The lines `Config files` and `Config sections` are slightly confusingly named. What's it's trying to say is `Config files searched`, `Config files found`, `Config sections searched`, and `Config sections found`.

**Comment by AimoE** [comment]
https://nils-werner.github.io/crestic/config/ says /etc/crestic.cfg

**Comment by nils-werner** [comment]
That's a typo, thanks. The output of the dry run is the real deal :-)

**Comment by AimoE** [comment]
Ok, I was sure it was something really simple.

This does reveal, though, that there are not many users. The larger user base, the better presentation details are kept clean.

**Comment by nils-werner** [comment]
Just for sake of completeness, the config file name changed to `config.cfg` in 8169601e

**Comment by codl** [comment]
> Just for sake of completeness, the config file name changed to `config.cfg` in [8169601](https://github.com/nils-werner/crestic/commit/8169601e8d1f072168fb6c46367912d3aff61fca)

is there a reason?

**Comment by nils-werner** [comment]
Yes, it's less awkward to have config files

```
/etc/crestic/config.cfg
/etc/crestic/conf.d/*
```

than

 ```
/etc/crestic.cfg
/etc/crestic/conf.d/*
```
