### ISSUE TITLE
Crestic is looking for config.cfg, not crestic.cfg

### ISSUE THREAD

**Issue by jgottlander** [nils-werner/crestic#34]
According to the docs, the name of the config file should be crestic.cfg, but when I'm debugging crestic it's looking for config.cfg.

When trying to backup i'm getting error message: "Fatal: nothing to backup, please specify target files/dirs".
It worked before when I used Arch, but just switched over to Fedora 37 and the same config doesn't work. Renaming it to config.cfg fixes the problem, but maybe good idea to change the docs if it's the new standard.
```
   Warning: Executing in debug mode. restic will not run, backups are not touched!
        Config files: /usr/share/crestic/config.cfg, /etc/crestic/config.cfg, /home/XXX/.config/crestic/config.cfg
   Config files used: 
     Config sections: global, global.backup, home, home.backup, home, home.backup
Config sections used: 
        Env sections: global.environ, global.backup.environ, home.environ, home.backup.environ, home.environ, home.backup.environ
   Env sections used: 
    Expanded command: restic backup
```

**Comment by nils-werner** [comment]
Oh right, the filename changed in 8169601e. To be honest I don't remember if it was intentional or by mistake, so sorry for that.
