### ISSUE TITLE
append config instead overwrite it

### ISSUE THREAD

**Issue by kuyagic** [nils-werner/crestic#35]
want to get the feature that can expand a exclude file based on the global one

**Comment by nils-werner** [comment]
Sorry I don't understand what you mean...

**Comment by kuyagic** [comment]
for example my global.cfg content is 
```
[global.backup]
iexclude-file: /opt/global.exclude
```

and my main.backend.cfg content is
```
[main]
repo: <REPO>
password-file: <FILE>

[main.backup]
iexclude-file: /opt/additional.exclude
```

Is it possible to combine the params which is allowed to pass multi-times and pass to restic which will result in
`restic backup --repo <REPO> --exclude-file /opt/global.exclude --exclude-file /opt/additional.exclude`

this will also apply to verbose or tag which can be pass multi-times to restic
Or can you make it an option for user to choose weather to overwrite it or combine them all to pass to restic.

Thank you.

**Comment by nils-werner** [comment]
Ah I see!

Right now that's not possible I'm afraid. Keys are always overwritten by more specific sections. All you can do right now is repeat the value

```
[global.backup]
iexclude-file: /opt/global.exclude

[main.backup]
iexclude-file:
    /opt/global.exclude
    /opt/additional.exclude
```

If I enabled [`ExtendedInterpolation`](https://docs.python.org/3/library/configparser.html#configparser.ExtendedInterpolation) the following could be possible:

```
[global.backup]
iexclude-file: /opt/global.exclude

[main.backup]
iexclude-file:
    ${global:exclude-file}
    /opt/additional.exclude
```

but I am not sure if that's really that useful...

**Comment by kuyagic** [comment]
Thank you for your help , that's very useful for me in many backup location situation.

**Comment by nils-werner** [comment]
Sorry can you say which solution worked for you? And as this is not yet merged into `master`... so if you close this I read it as you don't need it merged?

**Comment by nils-werner** [comment]
It's now enabled in 0.8.0
