### ISSUE TITLE
How to set environment variables using commands?

### ISSUE THREAD

**Issue by danlamanna** [nils-werner/crestic#36]
Is it possible to set an environment variable using a command? So instead of:
```
[@cloud.environ]
B2_ACCOUNT_ID: <MY_APPLICATION_KEY_ID>
B2_ACCOUNT_KEY: <MY_APPLICATION_KEY>
```

One could use:
```
[@cloud.environ]
B2_ACCOUNT_ID: <MY_APPLICATION_KEY_ID>
B2_ACCOUNT_KEY: pass backups/b2/account-key
```

**Comment by nils-werner** [comment]
Not inside crestic, sorry. But you can set a session wide environment variable that way in your `.bashrc`.

**Comment by danlamanna** [comment]
Do you think it's out of scope for the project? Because I have to set these environment variables differently per backup environment, which doesn't seem too unusual.

**Comment by nils-werner** [comment]
It's now in `master` and will be in the next release. Thanks for the suggestion!
