### ISSUE TITLE
Expand documentation/example

### ISSUE THREAD

**Issue by fdw** [nils-werner/crestic#4]
I'm thinking of using `crestic` as a wrapper around `restic`, but I can't quite figure out how to configure it. Could you maybe expand the example for the ini file?
For example, which options can I set? How can I backup multiple path for one preset?

Thank you!

**Comment by nils-werner** [comment]
Did you read [Usage](https://github.com/nils-werner/crestic#usage). I am not sure what else I should write... maybe you can show me where I should expand the documentation?

> For example, which options can I set?

any commandline option that restic offers.

> How can I backup multiple path for one preset?

Restic allows calls like `restic /dir1 /dir2`, which means you can set an option

    arguments: /dir1 /dir2

**Comment by fdw** [comment]
> > For example, which options can I set?

> any commandline option that restic offers.

Okay, thanks. And they're named the same, without the `--`, right?

Maybe stating this explicitely somewhere would help; at least, it would've helped me ;)

> `arguments: /dir1 /dir2`

Okay, I thought I might need something like `[/dir1, dir2]`. I could imagine having this in the example configuration.

> maybe you can show me where I should expand the documentation?
I think I understand it now, but if the example config uses many options, that makes it easier to copy from there. So maybe include some more `keep-within`, for example, to show that you can have several.

All in all, thank you for the answer and this tool! :)

**Comment by nils-werner** [comment]
> Okay, thanks. And they're named the same, without the `--`, right?

Exactly! OK, I'll try and clarify that a little bit more.

> Okay, I thought I might need something like `[/dir1, dir2]`

`arguments: ` are simply the remaining positional argument at the end of the commandline (the paths in `restic`s case). So no special tricks are required here.

**Comment by nils-werner** [comment]
Also, I'd recommend just setting 

    export CRESTIC_DRYRUN=1

and then playing around with the config file options and commandline options. It should become obvious after a few tries.

**Comment by fdw** [comment]
What I have learned so far that should probably be in the documentation:
- The environment variables should not be quoted, but escaped.
- The arguments and exclude patterns should be quoted.

**Comment by nils-werner** [comment]
Really? I am surprised by that. Can you give examples for these? i.e. what didn't work and what worked?

**Comment by fdw** [comment]
I tried to set a password for crestic, initially with quotes, and that didn't work - without quotes, it does. Also, the `%` in my password hat to be escaped to `%%`.

And some of my exclude patterns had `*` in them (or maybe it was the blanks in the pathnames), which apparently causes restic to backup multiple paths, but I haven't really investigated that, as quoting these strings helped.

**Comment by nils-werner** [comment]
> I tried to set a password for crestic, initially with quotes, and that didn't work - without quotes, it does. 

Quotes broke the `--password` argument? That is a bit surprising. Can you give a code example?

But I would anyways strongly advise against using `--password` and for `--password-file`. Otherwise your password will be visible to anyone who can run `ps aux` on your computer.

> Also, the `%` in my password hat to be escaped to `%%`.

I take it you are on Windows?

> And some of my exclude patterns had `*` in them

Yes, using `*` in options always needs to be escaped, or put in single quotes: To see why, try running

    echo --foo * asd

which will be expanded to

    echo --foo file1 file2 file3 asd

There is no way the command could know that `file2` and `file3` were actually from the `*` expansion. Instead the expansion needs to be done in side the command, and the `*` must be passed literally:

    echo --foo '*' asd

**Comment by fdw** [comment]
> Quotes broke the --password argument? That is a bit surprising. Can you give a code example?

I just tried it again, and it does not work if I have this in `crestic.ini`:
```
[blah.environ]
RESTIC_PASSWORD = "<password>"
```

However, it works if I have
```
[blah.environ]
RESTIC_PASSWORD = <password
```

> But I would anyways strongly advise against using --password and for --password-file. Otherwise your password will be visible to anyone who can run ps aux on your computer.

Makes sense, thank you :) For now, I just want to try `restic` (and `crestic`), this will likely not be the final configuration.

> I take it you are on Windows?

No :D The error seems to be somewhere in `configparser`: `configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: <part of my password>`

> Yes, using * in options always needs to be escaped, or put in single quotes

Yes, I know the behavior, but I had initially thought that `crestic` would quote the arguments.

**Comment by nils-werner** [comment]
These seem to be related with `ConfigParser`: INI files don't need quotes, and `%` are used for variable interpolation.

**Comment by fdw** [comment]
That works for me, but I thought it might be nice to mention that in the docs.
