### ISSUE TITLE
Feature request: Multiple commands

### ISSUE THREAD

**Issue by fdw** [nils-werner/crestic#5]
Hi, I hope I'm not annoying you yet ;)

I used to use borgmatic, which (more or less) called `backup prune check` if no command was specified. This is very helpful for automatic backups, as you only have to call one command.

I was wondering if you thought about implementing something similar as well. From playing with `crestic` and looking at the code, it seems that it wouldn't be easy to specify multiple commands like `crestic home backup forget prune check`. Do you think this use case (or a default of doing all when no command is specified) would be sensible to support? Or is it out of scope for crestic?

Thank you very much!

**Comment by nils-werner** [comment]
Hi @fdw, don't worry :-)

Unfortunately I must say this is out of scope for crestic. It is merely trying to mirror restic's API, plus the ability to put one or more options into a config file. If restic does not support multiple subcommands (it doesn't), neither should crestic.

Sorry to disappoint.

**Comment by fdw** [comment]
Hi @nils-werner ,
I added this functionality to a fork of crestic: https://github.com/fdw/crestic/tree/feature/multiple-commands
If you are interested, I can open a PR :)

Thanks again for your work and your help!

**Comment by nils-werner** [comment]
Some thoughts:

 1. One important feature of crestic is to be able to override config flags via commandline, i.e. `crestic backup --foo bar`. Does your implementation support passing commandline flags to the subcommands, i.e. `backup --foo bar prune --baz bay`? If yes, please implement a test for this, too
 1. The way you have to handle the return value for dryruns makes me wonder whether returning a 1 was a good idea in the first place...
 1. There are a lot of whitespace changes unrelated to this feature.
 1. You assume a `backup prune forget` default action. We can discuss whether this makes sense in the future, but right now it seems unrelated, too.

**Comment by fdw** [comment]
So, first off: Thanks for your comments. I wasn't sure you'd be interested, so I'm really grateful 🙂
Also, as a theme, this started out to scratch my own itch, and only later did I think of showing it to you. Some changes only make sense in that light.

> 1. One important feature of crestic is to be able to override config flags via commandline, i.e. crestic backup --foo bar. Does your implementation support passing commandline flags to the subcommands, i.e. backup --foo bar prune --baz bay? If yes, please implement a test for this, too

I personally don't use that feature, so I had no test for it. I would guess it still works, but I'll add a test.

> 2. The way you have to handle the return value for dryruns makes me wonder whether returning a 1 was a good idea in the first place...

To be honest, I don't quite like it either, but I didn't want to break compability 😉

> 3. There are a lot of whitespace changes unrelated to this feature.

That was probably my idea auto-formatting stuff. If you want a PR, I'm very open to change it to your requirements.

> 4. You assume a backup prune forget default action. We can discuss whether this makes sense in the future, but right now it seems unrelated, too.

Yup, it is unrelated. While coding it, I noticed that it would be quite easy to add (and the default I would want anyway), so I added it. For a PR, we can of course exclude it.

**Comment by fdw** [comment]
> Does your implementation support passing commandline flags to the subcommands, i.e. backup --foo bar prune --baz bay?

So, I wrote the test and it failed. Thinking more about it, the problem is that we need to distinguish commands from other arguments, which also might not start with `--`. I see several options, none of them obviously better than the others:
1. All the commands must be listed before the arguments, and all arguments will be passed to all commands (example: `crestic profile backup forget --exclude-file blah --keep-daily 7`). This is not really obvious or sensible, but the unwanted arguments should just be ignored by restic, so it should work.
2. We hardcode all possible restic commands. Then, something like `crestic profile backup --exclude-file blah forget --keep-daily 7` is possible, but the list of possible commands must be mainatined. This will fail if someone has an argument that is also a command (f.e `backup --exclude-file snapshots`).
3. We use a new argument (like `--command` or `--also`) to chain commands together, like so: `crestic profile backup --exclude-file blah --also forget --keep0-daily 7`. Also not obvious, but there is no need to hardcode the possible commands.
4. Maybe the easiest to implement: Each command must be contained in quotes: `crestic profile "backup --exclude-file blah" "forget --keep-daily 7"`. If you only have one command, the quotes should be optional. Still, not pretty.

What do you think?

**Comment by fdw** [comment]
Incidentally, I just found a problem with the current arg-parsing: `restic` allows multiple `--include` arguments for `restore`, but `crestic` fails when I try to do the same. 
Do you want me to open a separate bug for that?

**Comment by nils-werner** [comment]
I've pushed a fix for that to the `multiple-args` branch.

**Comment by fdw** [comment]
Thanks for the fix!

Would you still be interested in this, and if so, what would - in your opinion - be the best way to handle arguments for single commands?

**Comment by nils-werner** [comment]
I've given this a little bit more thought and I don't think this is worth it, given the issues that it brings. Sorry.

**Comment by fdw** [comment]
I agree that there is no clean way to do it. Still, thanks :)
