### ISSUE TITLE
Multiple presets per repository

### ISSUE THREAD

**Issue by dimejo** [nils-werner/crestic#9]
It would be great if we could configure a repository globally but still be able to configure presets separately. I hope this configuration example illustrates what I mean:
```
[global]
quiet:

# set global for all backups
[global.backup]
exclude-caches:

# set repo for all presets containing '@nas'
[@nas]
repo: sftp:my_nas:my_computer.restic
password-file: ~/config/restic/nas.password

[@nas.check]
read-data:

#configure 1st preset and inherit repo and password information from '@nas'
[work@nas.backup]
arguments: ~/work

[work@nas.forget]
keep-within: 31d

#configure 2nd preset and inherit repo and password information from '@nas'
[private@nas.backup]
arguments: ~/private

[private@nas.forget]
keep-daily: 90
```

**Comment by nils-werner** [comment]
I was thinking of something similar too when I started picking up the `home@nas` and `home@cloud` preset names (they're inspired by systemd unit parameters).

I haven't settled yet whether and how I want to introduce this sort of parameterization. So any feedback is welcome.

I don't see it as a high priority feature though as in the meantime it is not that terribly complicated to just write

```
[global]
quiet:

[global.backup]
exclude-caches:

[work@nas]
repo: sftp:my_nas:my_computer.restic
password-file: ~/config/restic/nas.password

[work@nas.check]
read-data:

[work@nas.backup]
arguments: ~/work

[work@nas.forget]
keep-within: 31d

[private@nas]
repo: sftp:my_nas:my_computer.restic
password-file: ~/config/restic/nas.password

[private@nas.check]
read-data:

[private@nas.backup]
arguments: ~/private

[private@nas.forget]
keep-daily: 90
```

**Comment by dimejo** [comment]
While you are correct that this can be done currently, it becomes confusing when you have more than 2 presets and even multiple repositories in your configuration file. Moreover it allows for shorter commands on the command line (which is always great) when working with the whole repository (e.g. `crestic @nas snapshots`)

**Comment by nils-werner** [comment]
I agree this would be nice, but it would introduce some of magical behaviour, especially when running commands on both `@nas` and `work@nas`.

I am not saying it cannot be done, but it needs some hard thinking and a proper design concept before it can be done.

**Comment by fdw** [comment]
To make this a bit more complicated, I'd like it the other way around: Have a shared "prefix" like `work` in your examples.

The reason is that I try to backup the same files to different repositories. It would be nice if I had to list the directories (and maybe some other settings) just once, instead of for every repo.

But I see how that would complicate things a lot 😉

**Comment by nils-werner** [comment]
One solution that I could imagine is to split preset names by `@`, and allow the user to combine any of the split presets.

```
[@nas]
repo: nas

[@cloud]
repo: cloud

[home@.backup]
arguments: ~

[work@.backup]
arguments: ~/work/
```

will yield

 - `home@nas`
 - `home@cloud`
 - `work@nas`
 - `work@cloud`

**Comment by fdw** [comment]
That sound like a good plan 🙂

**Comment by nils-werner** [comment]
Have a look at the [split branch](https://github.com/nils-werner/crestic/tree/split) for an initial test build.

**Comment by dimejo** [comment]
Closing as this was implemented with v0.4.0.

**Comment by dimejo** [comment]
Reopening as `@nas` does not work for me on the command line. It's working fine when used in the configuration file though.

**Comment by nils-werner** [comment]
Yes, that's by design. You always need to combine a prefix and a suffix.

**Comment by dimejo** [comment]
Well, I can of course work around that. And I fully understand if you don't want to implement that because it would probably make the code a lot more complex.
